var quotes = [
' "Believe you can and you\'re halfway there." - Theodore Roosevelt',
' "Nobody cares how much you know, until they know how much you care." - Theodore Roosevelt',
' "If we all did the things we are capable of doing, we would literally astound ourselves." - Thomas Edison',
' "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. - Thomas Edison',
' "Many of life\'s failures are made by people who did not realize how close they were to success when they gave up. - Thomas Edison',
' "Restlessness is discontent — and discontent is the first necessity of progress. Show me a thoroughly satisfied man — and I will show you a failure." - Thomas Edison',
' "Genius is one percent inspiration and 99 percent perspiration. I never did anything worth doing by accident, nor did any of my inventions come by accident; they came by work. - Thomas Edison',
' "You come back to the Hill now as you came back then. Once again in your memory let flash the vivid scenes that you will never forget. With the red dawn of a new college day and a new college generation come back across the campus and with that which thou hast in that heavy ragged suitcase of thine give a toast "To the Days that are Gone. - Thomas Wolfe',
' "Do not wish to be anything but what you are, and try to be that perfectly." - Saint Francis de Sales', 
' "Success is never final. Failure is never fatal. It\'s courage that counts." - Sam Rutigliano',
' "A man can make mistakes, but he isn\'t a failure until he starts blaming someone else." - Sam Rutigliano',
' "To win, you have to have the talent and desire - but desire is first." - Sam Snead',
' "Youth is not a time of life; it is a state of mind. Nobody grows old by merely living a number of years, but to give up enthusiasm wrinkles the soul." -Samuel Ullman',
' "Don\'t look back. Someone might be gaining on you. When you look back, you know how long you\'ve been going and that just might stop you from going any farther." - Satchel Paige',
' "Run your race. This applies to everyone and everything in life. To me, it means to follow your instincts and live a life you are proud of." - Shalane Flanagan',
' "Most men pursue pleasure with such breathless haste that they hurry past it." - Soren Kierkegaard',
' "Life can only be understood backwards; but it must be lived forwards." - Soren Kierkegaard',
' "I\'m called a superstar. Heck, the real superstar is a man or woman who is raising six kids on $150 a week and teaching them good values." - Spencer Haywood',
' "When a pitcher\'s throwing a spitball, don\'t worry, don\'t complain - just hit the dry side." - Stan Musial',
' "Intelligence is the ability to adapt to change." - Stephen Hawking',
' "Remember to look up at the stars and not down at your feet. And however difficult life may seem, there is always something you can do and succeed at. It matters that you don\'t just give up." - Stephen Hawking',
' "My favorite things in life don\'t cost any money. It\'s really clear that the most precious resource we all have is time." - Steve Jobs',
' "Your time is limited, so don\t waste it living someone else\'s life. Don\'t let the noise of others\' opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition." - Steve Jobs',
' "We didn’t come this far just to come this far." - Porky Spencer',
' "Anyone can stand tall on the high peaks. It is the people who survive the valleys between the peaks who will emerge the strongest." - Preston Pearson',
' "The greatest glory in living lies not in never falling, but in rising every time we fall." - Ralph Waldo Emerson',
' "You can never do a kindness too soon because you never know how soon it will be too late." - Ralph Waldo Emerson',
' "Don\'t be pushed by your problems. Be led by your dreams." - Ralph Waldo Emerson',
' "Nothing great was ever achieved without enthusiasm." - Ralph Waldo Emerson',
' "Ball don\'t lie." - Rasheed Wallace',
' "Wins and losses come a dime a dozen. But effort? Nobody can judge that. Because effort is between you and you." - Ray Lewis',
' "You don\'t learn to walk by following rules. You learn by doing, and by falling over." - Richard Branson',
' "In three words I can sum up everything I\'ve learned about life: It goes on." - Robert Frost',
' "There are those who look at things the way they are, and ask why. I dream of things that never were, and ask why not?" - Robert Kennedy',
' "You\'ll have bad times, but it\'ll always wake you up to the good stuff you weren\'t paying attention to." - Robin Williams',
' "We can\'t help everyone, but everyone can help someone." - Ronald Reagan',
' "You can only make so much money in life and only enjoy so many creature comforts. The important thing is to do something meaningful - to leave something behind." - Roone Arledge',
' "If you go through life worrying about all the bad things that can happen, you soon convince yourself that it’s best to do nothing at all." - Ross Perot',
' "Most people are about as happy as they make up their mind to be." - Abraham Lincoln',
' "In the end, it\'s not the years in your life that count. It\'s the life in your years." - Abraham Lincoln',
' "Whatever you are, be a good one." - Abraham Lincoln',
' "A person who never made a mistake never tried anything new." - Albert Einstein',
' "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning." - Albert Einstein',
' "Try not to become a man of success, but rather try to become a man of value." - Albert Einstein',
' "A calm and modest life brings more happiness than the pursuit of success combined with constant restlessness." - Albert Einstein',
' "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." - Albert Schweitzer',
' "When one door closes, another opens. But we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us." - Alexander Graham Bell',
' "Having Dean Smith ask you to redo the Carolina uniforms is like having God ask you to redo the uniforms for the archangels." - Alexander Julian',
' "Do a good day\'s work and act like somebody." - Andy Griffith',
' "Human greatness does not lie in wealth or power, but in character and goodness." - Anne Frank',
' "Move. As far as you can, as much as you can. Across the ocean, or simply across the river. Walk in someone else\'s shoes or at least eat their food. Open your mind, get up off the couch, move." - Anthony Bourdain',
]

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}